import { OwnershipOverviewCard } from "@/app/_components/cards/OwnershipOverviewCard";
import "@testing-library/jest-dom";
import { expect, test } from "@jest/globals";

test("Row span calculation for VehicleOverviewCard", () => {
  expect(OwnershipOverviewCard([]).props.style["gridRowEnd"]).toBe("span 5");

  // 3 active cars
  expect(
    OwnershipOverviewCard([
      {
        type: "car",
        make: "a",
        model: "a",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "car",
        make: "b",
        model: "b",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "car",
        make: "c",
        model: "c",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
    ]).props.style["gridRowEnd"]
  ).toBe("span 9");

  // 2 active + 1 sold car
  expect(
    OwnershipOverviewCard([
      {
        type: "car",
        make: "a",
        model: "a",
        sell_price: 1,
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "car",
        make: "b",
        model: "b",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "car",
        make: "c",
        model: "c",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
    ]).props.style["gridRowEnd"]
  ).toBe("span 13");

  // 1 active car, 1 active motorcycle, 1 sold car
  expect(
    OwnershipOverviewCard([
      {
        type: "car",
        make: "a",
        model: "a",
        sell_date: "2010-10-10",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "car",
        make: "b",
        model: "b",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "motorcycle",
        make: "c",
        model: "c",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
    ]).props.style["gridRowEnd"]
  ).toBe("span 14");

  // 2 active car 1 active motorcycle
  expect(
    OwnershipOverviewCard([
      {
        type: "car",
        make: "a",
        model: "a",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "car",
        make: "b",
        model: "b",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
      {
        type: "motorcycle",
        make: "c",
        model: "c",
        row: 0,
        trim: "",
        year: 0,
        color: "",
        plate: "",
        vin: "",
        fuel_type: "",
        purchase_date: "",
        purchase_price: 0,
        sell_date: "",
        sell_price: 0,
        avg_mileage: 0,
        avg_consumption: 0,
        refuel_data: [],
        odometer_data: [],
        insurance_data: [],
        maintenance_data: [],
        accident_data: [],
        ticket_data: [],
        details: false,
      },
    ]).props.style["gridRowEnd"]
  ).toBe("span 10");
});
